return function()
    https = require 'https'
    utf8 = require 'utf8'
    g3d = require 'libraries.g3d'
    lollipop = require 'libraries.lollipop'
    loveframes = require 'libraries.loveframes'
    moonshine = require 'libraries.moonshine'
    slab = require 'libraries.slab'
    suit = require 'libraries.suit'
    thirst = require 'libraries.thirst'
    class = require 'libraries.classic'
    baton = require 'libraries.baton'
    camera = require 'libraries.camera'
    collision = require 'libraries.collision'
    deep = require 'libraries.deep'
    discordrpc = require 'libraries.discordRPC'
    gamestate = require 'libraries.gamestate'
    gamejolt = require 'libraries.gamejolt'
    flux = require 'libraries.flux'
    knifeevent = require 'libraries.KnifeEvent'
    json = require 'libraries.json'
    luafft = require 'libraries.luafft'
    lume = require 'libraries.Lume'
    nativefs = require 'libraries.nativefs'
    timer = require 'libraries.timer'
    terminal = require 'libraries.Terminal'
end