return function()
    --TODO: Clean out this shitty mess of libraries --
    https = require 'https'
    breezefield = require 'libraries.breezefield'
    lollipop = require 'libraries.lollipop'
    loveframes = require 'libraries.loveframes'
    moonshine = require 'libraries.moonshine'
    slab = require 'libraries.slab'
    sti = require 'libraries.sti'
    sunlight = require 'libraries.sunlight'
    thirst = require 'libraries.thirst'
    windfield = require 'libraries.windfield'
    class = require 'libraries.classic'
    anim8 = require 'libraries.anim8'
    baton = require 'libraries.baton'
    bump = require 'libraries.bump'
    camera = require 'libraries.camera'
    luafft = require 'libraries.luafft'
    cartographer = require 'libraries.cartographer'
    collision = require 'libraries.collision'
    deep = require 'libraries.deep'
    discordrpc = require 'libraries.discordRPC'
    gamestate = require 'libraries.gamestate'
    gamejolt = require 'libraries.gamejolt'
    knifeevent = require 'libraries.KnifeEvent'
    json = require 'libraries.json'
    hc = require 'libraries.hc'
    lualzw = require 'libraries.Lualzw'
    lume = require 'libraries.Lume'
    lue = require 'libraries.lue'
    push = require 'libraries.push'
    nativefs = require 'libraries.nativefs'
    timer = require 'libraries.timer'
    xml = require 'libraries.xml'
end